add 'passed' job for required checks

diff --git a/.github/workflows/pr_checks.yaml b/.github/workflows/pr_checks.yaml
--- a/.github/workflows/pr_checks.yaml
+++ b/.github/workflows/pr_checks.yaml
@@ -67,6 +67,25 @@ jobs:
       kic-image: ${{ needs.build-docker-image.outputs.image }}
       load-local-image: true
 
+  # We need this step to fail the workflow if any of the previous steps failed or were cancelled.
+  # It allows to use this particular job as a required check for PRs.
+  # Ref: https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
+  passed:
+    runs-on: ubuntu-latest
+    needs:
+      - linters
+      - unit-tests
+      - integration-tests
+      - conformance-tests
+      - build-docker-image
+      - e2e-tests
+    if: always()
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "Some jobs failed or were cancelled."
+          exit 1
+
   test-reports:
     needs:
       - should-run-with-secrets
